export default {
  common: {
    title: "Freeconomy",
    cancel: "Annuler",
    name: "Nom",
    description: "Description",
    icon: "Icone",
    save: "Enregistrer",
    saveAndNew: "Enregistrer et Nouveau",
    loading: "Chargement",
    price: "Prix",
    back: "Retour",
    edit: "Modifier",
    remove: "Supprimer",
    removeName: "Supprimer %{name} ?",
  },
  login: {
    buttonWithGoogle: "Connexion avec Google",
    line1: "Gérez vos comptes et sachez exactement ce que vous dépensez.",
    line2: "Categorisez vos transactions pour connaître vos budgets mensuels !",
    locally: "Ou utilisez l'application localement, toutes vos données seront supprimées lors de la deconnexion.",
    welcome: "Bienvenue dans Freeconomy",
  },
  sideBar: {
    home: "Accueil",
    categories: "Catégories",
    reports: "Rapports",
    sync: "Synchroniser",
    logout: "Déconnexion",
    logoutConfirm: "Se déconnecter ?",
    logoutConfirmText: `Êtes-vous sûr de vouloir vous déconnecter ?
    Toutes les données non synchronisées seront supprimées.
    Vérifiez d'avoir synchronisé une dernière fois avant de vous déconnecter.`,
  },
  walletsView: {
    loading: "Chargement de comptes",
    add: "Ajouter un Compte",
    wallets: "Comptes",
  },
  addWalletView: {
    currencyCode: "Nom de la monnaie",
    symbol: "Symbole",
  },
  transactionsView: {
    addTransaction: "Ajouter une opération",
    addTransfert: "Ajouter un virement",
    importFromCSV: "Importer depuis un CSV",
    loading: "Chargement des transactions",
  },
  addTransactionView: {
    beneficiary: "Bénéficiaire",
    comment: "Commentaire",
  },
  categoriesView: {
    loading: "Chargement des catégories",
    addCategory: "Ajouter une Catégorie",
  },
  defaultCategories: {
    insurance: "Assurance",
    healthInsurance: "Assurance-Maladie",
    others: "Autres",
    bank: "Banque",
    bar: "Bar",
    presentTo: "Cadeaux - offerts",
    presentFrom: "Cadeaux - reçus",
    cinema: "Cinema",
    donations: "Dons",
    fuel: "Essence",
    studies: "Études",
    groceries: "Faire les courses",
    party: "Fête",
    hotel: "Hôtel",
    tax: "Impôts",
    interests: "Intérêts",
    game: "Jeux d'argent",
    laundry: "Linge",
    leisure: "Loisir",
    rent: "Loyer",
    home: "Maison",
    parking: "Parking",
    income: "Recettes",
    meal: "Repas",
    restaurant: "Restaurant",
    shopping: "Shopping",
    care: "Soin personnels",
    phone: "Téléphone",
    transport: "Transport",
    holidays: "Vacances",
    clothes: "Vêtements",
    car: "Voiture",
    travel: "Voyage",
  },
  defaultWallets: {
    cash: "Porte Monnaie",
    cashDescription: "Porte Monnaie",
    bank: "Compte courant",
    bankDescription: "Compte avec carte de crédit",
  },
  deleteCategoryView: {
    areYouSure: "Êtes vous sûr de vouloir supprimer la catégorie %{name} ?",
  },
  deleteWalletView: {
    areYouSure: "Êtes vous sûr de vouloir supprimer le compte %{name} et toute ses opérations ?",
  },
  reportPie: {
    title: "Rapport des dépenses",
  },
};
